### ISSUE TITLE
Implement multistage build

### ISSUE THREAD

**Issue by TitusKirch** [fsr5-fhaachen/portals#336]
N/A

**Comment by simonostendorf** [comment]
Not required for Laravel applications. 
Everything in the current image (php, roadrunner, all source files etc.) is needed to run the application. 

Multi-stage builds do not make sense here in my opinion.

**Comment by TitusKirch** [comment]
You forgot the client with all the node dependencies, I think we can save a lot here by only using the built client in the image.
