### ISSUE TITLE
Update docker/login-action from 2 to 3

### ISSUE THREAD

**Issue by TitusKirch** [fsr5-fhaachen/portals#484]
Something doesn't work (see https://github.com/fsr5-fhaachen/portals/actions/runs/6266077324)

**Comment by simonostendorf** [comment]
Just restart the ci run. There was a rate limit (`API rate limit exceeded`).

But the title here is `docker/login-action from 2 to 3` and the linked ci run is for a dependabot update on `@tailwindcss/typography`. What do you need me to fix?
